spring:
  security:
    user:
      name: user
      password: 123456
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  swagger-ui.path: /api-docs