spring:
  security:
    user:
      name: user
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create